### ISSUE TITLE
Some lecture notebooks I made may be useful as training materials

### ISSUE THREAD

**Issue by tztsai** [Cambridge-ICCS/ml-training-material#46]
[Here](https://drive.google.com/drive/folders/19zzLUg6JFn-S2HkrdDwtke1Sp661ftuu?usp=drive_link) are a series of lecture notebooks I prepared as an ML instructor when I was in college (except `review.docx`). We can use them freely for the ML workshop.

**Comment by jatkinson1000** [comment]
Thank you for this.
I would encourage you to add this information to the summer school issue rather than this repository, as this space is intended for issues related to the existing material which is geared at providing practical capabilities with PyTorch and an understanding of how deep learning works in practice.

The workbooks you linked look really good and I will take a closer look for my personal education, thank you.
If you wish to work them into a similar format with supporting material for delivery please open singular issues with a clear description and a suggestion of a pull request.
